language: node_js
node_js: 
  - "stable"
cache:
  directories:
    - "node_modules"
deploy:
  provider: lambda
  access_key_id: ${ACCESS_KEY}
  secret_access_key: ${SECRET_KEY}
  function_name: ${FUNCTION_NAME}
  edge: true # opt in to dpl v2
  on:
    branches:
      only:
        - AWS-Lambda
