language: node_js
node_js: 
  - "stable"
cache:
  directories:
    - "node_modules"
deploy:
  provider: lambda
  access_key_id: <encrypted access_key_id>
  secret_access_key: <encrypted secret_access_key>
  function_name: <function_name>
  edge: true # opt in to dpl v2
